# Generated by Django 4.0 on 2022-04-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_mazmuni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
    ]
